import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appTitle: "SmartFarm AI",
    subTitle: "AI-Driven Unified Smart Farming Platform",
    dashboard: "Dashboard",
    weather: "Weather",
    cropDetection: "Crop Disease Detection",
    farmerAssistant: "AI Farmer Assistant",
    community: "Community",
    library: "Agriculture Library",
    planner: "Smart Crop & Harvest Planner",
    predictionHistory: "Prediction History",
    aiReports: "AI Reports",
    voiceAssistant: "Voice Assistant",
    settings: "Settings",
    
    // Header
    greeting: "Good Morning, Farmer 👋",
    greetingSub: "Monitor your crops and get AI-powered insights.",
    language: "Language",
    
    // Dashboard Cards & Widgets
    cropHealth: "Crop Health",
    healthy: "Healthy",
    atRisk: "At Risk",
    critical: "Critical",
    soilMoisture: "Soil Moisture",
    temperature: "Temperature",
    humidity: "Humidity",
    rainStatus: "Rain Status",
    noRain: "No Rain",
    rainDetected: "Rain Detected",
    esp32SensorMonitoring: "ESP32 Sensor Telemetry",
    liveSensorFeed: "Real-time IoT environmental data directly from ESP32 micro-controller",
    aiInsights: "AI Insights",
    systemStatus: "System Status",
    recentActivity: "Recent Sensor Activity",
    weatherForecast: "Local Field Weather",
    todaysWeather: "Today's Weather",
    viewForecast: "View Forecast",
    nextActivity: "Next Farming Activity",
    weatherAlertWidget: "Weather Alert",
    latestLibraryTopic: "Latest Agriculture Topic",
    viewPlanner: "Open Planner",
    exploreLibrary: "Explore Library",

    // Weather Page
    weatherTitle: "Weather Forecast & Alerts",
    weatherSubtitle: "Monitor weather conditions and receive farming-related weather alerts.",
    currentLocation: "Selected Location",
    searchLocationPlaceholder: "Search city or district...",
    useCurrentLocation: "Use Current Location",
    currentWeather: "Current Weather",
    sevenDayForecast: "7-Day Forecast",
    hourlyForecast: "Hourly Forecast",
    farmerAlerts: "Farmer Weather Alerts",
    cropWeatherInsights: "Crop Weather Insights",
    fieldVsWeather: "Field vs Weather Comparison",
    externalWeather: "External Weather Forecast",
    esp32FieldSensor: "ESP32 Field Sensor",
    rainProbability: "Rain Probability",
    windSpeed: "Wind Speed",
    uvIndex: "UV Index",

    // Agriculture Library Page
    libraryTitle: "Agriculture Library",
    librarySubtitle: "Explore trusted agricultural knowledge for better crop management.",
    searchLibraryPlaceholder: "Search agricultural information...",
    libraryCategories: "Knowledge Categories",
    cropOverview: "Crop Overview",
    growingConditions: "Growing Conditions",
    commonDiseases: "Common Diseases",
    commonPests: "Common Pests",
    irrigationReq: "Irrigation",
    soilReq: "Soil Requirements",
    cropManagement: "Crop Management",
    harvestInfo: "Harvest Information",
    askAiAboutTopic: "Ask AI Assistant About This Topic",

    // Farming Planner Page (Smart Crop & Harvest Planner)
    plannerTitle: "Smart Crop & Harvest Planner",
    plannerSubtitle: "Pre-planting crop calendar, dynamic stage timeline, weather-aware schedule & harvest forecasting.",
    cropPlanningTitle: "Crop Pre-Planning & Configuration",
    cropPlanningSubtitle: "Select your crop, regional location, and intended planting date to calculate real-time growth timelines and harvest dates.",
    createPlan: "Create Farm Plan",
    selectCrop: "Select Crop",
    locationCity: "Location / District",
    stateLabel: "State",
    districtLabel: "District / Agro Zone",
    quickMonthPreset: "Quick Planting Month",
    selectState: "Select State",
    selectDistrict: "Select District",
    plantingDate: "Planting Date",
    expectedHarvest: "Expected Harvest Date",
    expectedHarvestHeading: "Expected Harvesting Period",
    harvestStart: "Harvest Start",
    bestHarvestPeriod: "Best Harvesting Period",
    harvestEnd: "Harvest End",
    bestHarvestSeason: "Best Regional Season for Harvesting",
    growthDuration: "Expected Growth Duration",
    recommendedPlantingSeason: "Recommended Planting Season",
    harvestCountdown: "Harvest Countdown",
    daysRemaining: "days until harvest window",
    daysToPlant: "days until planned planting",
    todayStatus: "Current Stage Active",
    planningEstimateNote: "Planning estimate — verify with local agricultural guidance (TNAU / KVK).",
    farmSize: "Farm Size (Acres)",
    cropTimeline: "Crop Growth Stage Timeline",
    cropCalendarHeading: "Dynamic Crop Growth Timeline & Calendar",
    stageActivities: "Key Stage Practices",
    weatherConsiderations: "Weather Considerations",
    farmActivities: "Farm Activities & Weather Schedule",
    activityChecklist: "Farming Activities Checklist",
    filterAll: "All Activities",
    filterIrrigation: "Irrigation",
    filterFertilizer: "Fertilizer / Nutrition",
    filterDisease: "Disease Monitoring",
    filterPest: "Pest Monitoring",
    filterHarvest: "Harvesting",
    weatherReminder: "Weather-Aware Alert",
    weatherRiskAlert: "Live Weather Impact On Schedule",
    aiAdvisoryHeading: "AI Agronomic Advisory & Schedule Intelligence",
    aiAdvisorySub: "Personalized pre-planning guidance synthesized from Agricultural Knowledge Base, crop growth stage, and local weather forecasts.",
    generateAiAdvisory: "Generate AI Farming Advice",
    generatingAi: "Synthesizing Agronomic Guidance...",
    listenAudio: "Listen Advice (Audio)",
    stopAudio: "Stop Audio",
    openInAssistant: "Discuss with AI Assistant",
    askAiAboutPlan: "Ask AI About This Plan",
    monthlyCalendar: "Monthly Calendar",
    upcomingActivities: "Upcoming Activities",
    completedActivities: "Completed Activities",
    markCompleted: "Mark Completed",
    statusUpcoming: "Upcoming",
    statusInProgress: "In Progress",
    statusCompleted: "Completed",
    harvestReadiness: "Harvest Readiness Signs",
    maturityTips: "Maturity & Quality Criteria",
    days: "days",

    // Actions
    viewReport: "View Report",
    analyzeCrop: "Analyze Crop",
    downloadPdf: "Download PDF",
    printReport: "Print Report",
    generateReport: "Generate AI Report",
    askAssistant: "Ask AI Assistant",
    savePrediction: "Save Prediction",
    createPost: "Create Post",
    reply: "Reply",
    like: "Like",
    
    // Disease Detection
    detectionTitle: "AI Crop Disease Detection",
    detectionSubtitle: "Upload a leaf image to detect diseases in Tomato, Potato, and Brinjal.",
    predictionResult: "Prediction Result",
    aiExplanation: "AI Explanation (LIME Heatmap)",
    predictionDetails: "Prediction Details",

    // Chatbot & Voice
    chatTitle: "AI Farmer Assistant",
    chatSubtitle: "Ask questions about crop diseases, crop management, and farming practices.",
    voiceTitle: "Voice Assistant",
    voiceSubtitle: "Speak in English or Tamil to receive spoken AI agronomic advice.",

    // History & Reports
    historyTitle: "Prediction History",
    historySubtitle: "Review previous Solanaceae crop leaf scans and diagnostic advisories.",
    reportTitle: "AI Report",

    // Settings
    profile: "Farmer Profile",
    notifications: "Notification Preferences",
    systemDiagnostics: "System Diagnostics",
  },
  ta: {
    appTitle: "ஸ்மார்ட்ஃபார்ம் AI",
    subTitle: "செயற்கை நுண்ணறிவு அடிப்படையிலான நவீன விவசாய தளம்",
    dashboard: "டாஷ்போர்டு",
    weather: "வானிலை",
    cropDetection: "பயிர் நோய் கண்டறிதல்",
    farmerAssistant: "AI விவசாய உதவியாளர்",
    community: "சமூகம்",
    library: "வேளாண்மை நூலகம்",
    planner: "ஸ்மார்ட் பயிர் & அறுவடை திட்டமிடுதல்",
    predictionHistory: "கணிப்பு வரலாறு",
    aiReports: "AI அறிக்கைகள்",
    voiceAssistant: "குரல் உதவியாளர்",
    settings: "அமைப்புகள்",
    
    // Header
    greeting: "காலை வணக்கம், விவசாயி 👋",
    greetingSub: "உங்கள் பயிர்களைக் கண்காணித்து AI பரிந்துரைகளைப் பெறுங்கள்.",
    language: "மொழி",
    
    // Dashboard Cards & Widgets
    cropHealth: "பயிர் ஆரோக்கியம்",
    healthy: "ஆரோக்கியமானது",
    atRisk: "அபாய நிலை",
    critical: "கடுமையான நிலை",
    soilMoisture: "மண் ஈரப்பதம்",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    rainStatus: "மழை நிலை",
    noRain: "மழை இல்லை",
    rainDetected: "மழை பெய்கிறது",
    esp32SensorMonitoring: "சென்சார் கண்காணிப்பு",
    liveSensorFeed: "ESP32 சாதனத்திலிருந்து நேரடி சுற்றுச்சூழல் அளவீடுகள்",
    aiInsights: "AI நுண்ணறிவுகள்",
    systemStatus: "கணினி நிலை",
    recentActivity: "சமீபத்திய சென்சார் செயல்பாடுகள்",
    weatherForecast: "உள்ளூர் வானிலை",
    todaysWeather: "இன்றைய வானிலை",
    viewForecast: "முன்னறிவிப்பைப் பார்",
    nextActivity: "அடுத்த விவசாய செயல்பாடு",
    weatherAlertWidget: "வானிலை எச்சரிக்கை",
    latestLibraryTopic: "சமீபத்திய வேளாண் செய்தி",
    viewPlanner: "திட்டமிடுபவரைத் திறக்கவும்",
    exploreLibrary: "நூலகத்தை ஆராயுங்கள்",

    // Weather Page
    weatherTitle: "வானிலை முன்னறிவிப்பு மற்றும் எச்சரிக்கைகள்",
    weatherSubtitle: "வானிலை நிலைகளைக் கண்காணித்து விவசாய எச்சரிக்கைகளைப் பெறுங்கள்.",
    currentLocation: "தேர்ந்தெடுக்கப்பட்ட இடம்",
    searchLocationPlaceholder: "நகரம் அல்லது மாவட்டத்தைத் தேடுங்கள்...",
    useCurrentLocation: "தற்போதைய இடத்தைப் பயன்படுத்து",
    currentWeather: "தற்போதைய வானிலை",
    sevenDayForecast: "7 நாள் வானிலை முன்னறிவிப்பு",
    hourlyForecast: "மணிநேர வானிலை",
    farmerAlerts: "விவசாயி வானிலை எச்சரிக்கைகள்",
    cropWeatherInsights: "பயிர் வானிலை தகவல்கள்",
    fieldVsWeather: "நிலப்பரப்பு vs வானிலை ஒப்பீடு",
    externalWeather: "வெளிப்புற வானிலை முன்னறிவிப்பு",
    esp32FieldSensor: "ESP32 நிலப்பரப்பு சென்சார்",
    rainProbability: "மழை வாய்ப்பு",
    windSpeed: "காற்றின் வேகம்",
    uvIndex: "UV குறியீடு",

    // Agriculture Library Page
    libraryTitle: "வேளாண்மை நூலகம்",
    librarySubtitle: "சிறந்த பயிர் மேலாண்மைக்கு நம்பகமான வேளாண் அறிவை ஆராயுங்கள்.",
    searchLibraryPlaceholder: "விவசாய தகவல்களைத் தேடுங்கள்...",
    libraryCategories: "அறிவுப் பிரிவுகள்",
    cropOverview: "பயிர் மேலோட்டம்",
    growingConditions: "வளரும் சூழ்நிலைகள்",
    commonDiseases: "பொதுவான நோய்கள்",
    commonPests: "பொதுவான பூச்சிகள்",
    irrigationReq: "நீர்ப்பாசனம்",
    soilReq: "மண் தேவைகள்",
    cropManagement: "பயிர் மேலாண்மை",
    harvestInfo: "அறுவடைத் தகவல்கள்",
    askAiAboutTopic: "இந்த தலைப்பைப் பற்றி AI இடம் கேள்",

    // Farming Planner Page (Smart Crop & Harvest Planner)
    plannerTitle: "ஸ்மார்ட் பயிர் & அறுவடை திட்டமிடுதல்",
    plannerSubtitle: "விதைப்புக்கு முந்தைய பயிர் காலண்டர், வளர்ச்சி நிலைகள், வானிலை அடிப்படையிலான அட்டவணை & அறுவடை முன்னறிவிப்பு.",
    cropPlanningTitle: "பயிர் முன்-திட்டமிடல் & கட்டமைப்பு",
    cropPlanningSubtitle: "நிகழ்நேர வளர்ச்சி நிலைகள் மற்றும் அறுவடை தேதிகளைக் கணக்கிட உங்கள் பயிர், இடம் மற்றும் திட்டமிடப்பட்ட விதைப்பு தேதியைத் தேர்வுசெய்யவும்.",
    createPlan: "பண்ணைத் திட்டம் உருவாக்கு",
    selectCrop: "பயிரைத் தேர்ந்தெடு",
    locationCity: "இடம் / மாவட்டம்",
    stateLabel: "மாநிலம்",
    districtLabel: "மாவட்டம் / வேளாண் பகுதி",
    quickMonthPreset: "விரைவு விதைப்பு மாதம்",
    selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    selectDistrict: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    plantingDate: "விதைப்பு தேதி",
    expectedHarvest: "எதிர்பார்க்கப்படும் அறுவடை தேதி",
    expectedHarvestHeading: "எதிர்பார்க்கப்படும் அறுவடை காலம்",
    harvestStart: "அறுவடை தொடக்கம்",
    bestHarvestPeriod: "சிறந்த அறுவடை காலம்",
    harvestEnd: "அறுவடை முடிவு",
    bestHarvestSeason: "பகுதிக்கேற்ற சிறந்த அறுவடை பருவம்",
    growthDuration: "மொத்த வளர்ச்சி காலம்",
    recommendedPlantingSeason: "பரிந்துரைக்கப்பட்ட விதைப்பு பருவம்",
    harvestCountdown: "அறுவடை கவுண்டவுன்",
    daysRemaining: "நாட்கள் அறுவடைக்கு உள்ளன",
    daysToPlant: "நாட்கள் விதைப்புக்கு உள்ளன",
    todayStatus: "தற்போதைய நிலை செயல்பாட்டில் உள்ளது",
    planningEstimateNote: "திட்டமிடல் மதிப்பீடு — உள்ளூர் வேளாண் விரிவாக்க அலுவலர் / KVK வழிகாட்டுதலுடன் சரிபார்க்கவும்.",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    cropTimeline: "பயிர் வளர்ச்சி நிலை காலவரிசை",
    cropCalendarHeading: "டைனமிக் பயிர் வளர்ச்சி காலவரிசை & நாட்காட்டி",
    stageActivities: "முக்கிய நிலை மேலாண்மை பணிகள்",
    weatherConsiderations: "வானிலை தாக்கங்கள் & முன்னெச்சரிக்கை",
    farmActivities: "விவசாய செயல்பாடுகள் & வானிலை அட்டவணை",
    activityChecklist: "விவசாய பணிகள் சரிபார்ப்புப் பட்டியல்",
    filterAll: "அனைத்து பணிகள்",
    filterIrrigation: "நீர்ப்பாசனம்",
    filterFertilizer: "உரம் / ஊட்டச்சத்து",
    filterDisease: "நோய் கண்காணிப்பு",
    filterPest: "பூச்சி கண்காணிப்பு",
    filterHarvest: "அறுவடை பணிகள்",
    weatherReminder: "வானிலை எச்சரிக்கை அறிவிப்பு",
    weatherRiskAlert: "அட்டவணை மீதான நேரடி வானிலை தாக்கம்",
    aiAdvisoryHeading: "AI வேளாண் ஆலோசனை & அறிவார்ந்த அட்டவணை",
    aiAdvisorySub: "வேளாண் நூலக அறிவு, பயிர் வளர்ச்சி நிலை மற்றும் உள்ளூர் வானிலை முன்னறிவிப்பின் அடிப்படையில் உருவாக்கப்பட்ட ஆலோசனைகள்.",
    generateAiAdvisory: "AI விவசாய ஆலோசனையைப் பெறுங்கள்",
    generatingAi: "வேளாண் ஆலோசனைகள் தொகுக்கப்படுகின்றன...",
    listenAudio: "ஆலோசனையைக் கேள் (ஆடியோ)",
    stopAudio: "ஆடியோவை நிறுத்து",
    openInAssistant: "AI உதவியாளரிடம் விரிவாகக் கேள்",
    askAiAboutPlan: "இந்த திட்டத்தைப் பற்றி AI இடம் கேள்",
    monthlyCalendar: "மாதாந்திர நாட்காட்டி",
    upcomingActivities: "வரவிருக்கும் செயல்பாடுகள்",
    completedActivities: "முடிவடைந்த செயல்பாடுகள்",
    markCompleted: "முடிந்தது என குறிக்கவும்",
    statusUpcoming: "வரவிருப்பது",
    statusInProgress: "செயல்பாட்டில் உள்ளது",
    statusCompleted: "முடிவடைந்தது",
    harvestReadiness: "அறுவடை முதிர்ச்சி அறிகுறிகள்",
    maturityTips: "தரம் மற்றும் முதிர்ச்சி அளவுகோல்கள்",
    days: "நாட்கள்",

    // Actions
    viewReport: "அறிக்கையைப் பார்",
    analyzeCrop: "பயிரை ஆய்வு செய்",
    downloadPdf: "PDF பதிவிறக்கு",
    printReport: "அச்சிடு",
    generateReport: "AI அறிக்கை உருவாக்கு",
    askAssistant: "AI இடம் கேள்",
    savePrediction: "சேமிக்கவும்",
    createPost: "பதிவு உருவாக்கு",
    reply: "பதிலளி",
    like: "விருப்பம்",

    // Disease Detection
    detectionTitle: "AI பயிர் நோய் கண்டறிதல்",
    detectionSubtitle: "தக்காளி, உருளைக்கிழங்கு மற்றும் கத்தரி இலைகளைப் பதிவேற்றி நோய்களைக் கண்டறியவும்.",
    predictionResult: "கணிப்பு முடிவு",
    aiExplanation: "AI விளக்கம் (LIME Heatmap)",
    predictionDetails: "கணிப்பு விவரங்கள்",

    // Chatbot & Voice
    chatTitle: "AI விவசாய உதவியாளர்",
    chatSubtitle: "பயிர் நோய்கள், பயிர் மேலாண்மை மற்றும் விவசாய சந்தேகங்களைக் கேட்கலாம்.",
    voiceTitle: "குரல் உதவியாளர்",
    voiceSubtitle: "தமிழ் அல்லது ஆங்கிலத்தில் பேசி AI விவசாய ஆலோசனைகளைப் பெறுங்கள்.",

    // History & Reports
    historyTitle: "கணிப்பு வரலாறு",
    historySubtitle: "முந்தைய இலை சோதனைகள் மற்றும் AI பரிந்துரைகளை மதிப்பாய்வு செய்யவும்.",
    reportTitle: "AI அறிக்கை",

    // Settings
    profile: "விவசாயி சுயவிவரம்",
    notifications: "அறிவிப்பு விருப்பங்கள்",
    systemDiagnostics: "கணினி பரிசோதனை",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = (lang) => {
    setLanguage(lang || (language === 'en' ? 'ta' : 'en'));
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
